loki.source.docker "containers" {
  host = "unix:///var/run/docker.sock"
  targets = []
  forward_to = [loki.write.monitoring.receiver]

  relabel_rules = [
    rule {
      source_labels = ["__meta_docker_container_name"]
      target_label  = "container"
    }
  ]
}

loki.source.file "system" {
  targets = [
    { __path__ = "/var/log/syslog", job = "syslog" },
    { __path__ = "/var/log/auth.log", job = "auth" }
  ]
  forward_to = [loki.write.monitoring.receiver]
}

loki.write "monitoring" {
  endpoint {
    url = "http://10.1.1.4:3100/loki/api/v1/push"
  }
  external_labels = {
    source = "app-vm"
  }
}
