scrape_configs:
  - job_name: 'whoknows'
    static_configs:
      - targets: ['whoknows-dev:8080']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8081' ]


