scrape_configs:
  - job_name: 'whoknows'
    static_configs:
      - targets: ['10.0.0.4:8080']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.0.0.4:9100']

  - job_name: 'loki'
    static_configs:
      - targets: ['10.0.0.4:3100']

  - job_name: 'alloy'
    static_configs:
      - targets: ['10.0.0.4:12345']
