name: Continuous Delivery

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_GITHUB_USERNAME: ${{ github.actor }}

permissions:
    contents: read
    packages: write
    attestations: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.4.x'

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4

      - name: Print version
        run: echo "VERSION=${{ steps.gitversion.outputs.semVer }}"


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_GITHUB_USERNAME }}
          password: ${{ env.GITHUB_TOKEN }}

      - name: Build and Push App Image
        run: |
          VERSION=${{ steps.gitversion.outputs.semVer }}
          docker buildx build \
            --file ./Dockerfile.prod \
            --tag ghcr.io/dvk-devops/dvk-project:${VERSION} \
            --tag ghcr.io/dvk-devops/dvk-project:latest \
            --platform linux/amd64 \
            --cache-from=type=registry,ref=ghcr.io/dvk-devops/dvk-project:latest \
            --cache-to=type=registry,ref=ghcr.io/dvk-devops/dvk-project:latest,mode=max \
            --push .

      - name: Build and Push Nginx Image
        run: |
          docker buildx build \
            --file nginx/Dockerfile \
            --tag ghcr.io/dvk-devops/nginx:latest \
            --platform linux/amd64 \
            --push \
            ./nginx

      - name: Create Git Tag
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=${{ steps.gitversion.outputs.semVer }}
          git tag v${VERSION}
          git push origin v${VERSION}

